# Generated by Django 4.2 on 2024-10-17 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rentalorder_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='phone',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='rentalorderitem',
            name='rental_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.rentalorder'),
        ),
    ]
