# Generated by Django 4.2 on 2024-11-25 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_product_category_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fecha',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
    ]
